version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5555:5432"
    restart: unless-stopped

  angular-frontend:
    container_name: angular_container
    build:
      dockerfile: Dockerfile
      context: ./angular-frontend
    ports:
      - "4200:80"


  app:
    container_name: app_container
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8080:8080"
    depends_on:
    - postgres

volumes:
  postgres:
