name: Workflow 1

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: First
        run: echo "First"
      - name: Github
        run: ${{ toJSON(github) }}